[alembic]
script_location = .
sqlalchemy.url = postgresql://%(R2R_POSTGRES_USER)s:%(R2R_POSTGRES_PASSWORD)s@%(R2R_POSTGRES_HOST)s:%(R2R_POSTGRES_PORT)s/%(R2R_POSTGRES_DBNAME)s

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
